name: push_and_publish_to_gh-pages

on:
  push:
    branches: [ main ]

jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Instalando Python 3.12
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.12

      - name: Instalando dependencias de Python
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Generando los ficheros HTML
        run: |
          make html

      - name: Creando repositorio y commit de los ficheros HTML generados
        run: |
          cd build/html/
          git init
          touch .nojekyll
          git config --global --add safe.directory /github/workspace/build/html
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'

      - name: Fuerza el push al directorio gh-pages
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./build/html
